# -*- coding: utf-8 -*-


LARGEUR_DE_TUILE = 20
HAUTEUR_DE_TUILE = 20
NBR_COLONNES = 30 # NCOLS
NBR_LIGNES = 40 # NROWS
LARGEUR_FENETRE = NBR_COLONNES * LARGEUR_DE_TUILE
HAUTEUR_FENETRE = NBR_LIGNES * HAUTEUR_DE_TUILE
DIMENSION_FENETRE = (LARGEUR_FENETRE, HAUTEUR_FENETRE)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
YELLOW = (255,255,0)
RED = (255, 0,0)
STOP = 0
UP = 1
DOWN = 2
LEFT = 3
RIGHT = 4


PACMAN = 0
